### ISSUE TITLE
xtc-cli 0.2.1 install fails with `config is not defined`

### ISSUE THREAD

**Issue by SimonHarte** [MarcDiethelm/xtc-cli#1]
``` bash
$ xtc -V
0.2.1
$ xtc install

xtc install

[?] Your project will be set up in /xtc-test Ok? Yes
Getting list of xtc versions from npm...
[?] Choose a version to install: 0.8.0-beta8

Unable to write xtcfile.
Reason: config is not defined


ReferenceError: config is not defined
    at /usr/local/lib/node_modules/xtc-cli/bin/xtc-cli.js:246:53
    at _fulfilled (/usr/local/lib/node_modules/xtc-cli/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/xtc-cli/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/xtc-cli/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/xtc-cli/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/xtc-cli/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:664:11)
```

**Comment by MarcDiethelm** [comment]
Thanks. Will fix ASAP.
